### ISSUE TITLE
Challenge 30  Rahul333#8724

### ISSUE THREAD

**Issue by Sai3Rahul** [scaleracademy/scaler-september-open-source-challenge#166]
name : Sai Rahul
github_user_name: Sai3Rahul

**Comment by Sai3Rahul** [comment]
Forked Repository URL : https://github.com/Sai3Rahul/scaler-september-open-source-challenge
![Screenshot 2022-09-02 190313](https://user-images.githubusercontent.com/104320194/188158334-439f5d98-13cf-4f05-99e7-a616e19b3120.jpeg)

**Comment by Sai3Rahul** [comment]
![Screenshot 2022-09-03 201849](https://user-images.githubusercontent.com/104320194/188275901-ebc76cf5-7db0-400e-8e8b-6c15444a3e5d.jpeg)

**Comment by Sai3Rahul** [comment]
![Screenshot 2022-09-04 170036](https://user-images.githubusercontent.com/104320194/188311102-e3e5b489-db8a-49e5-b830-c07be8221f9b.jpeg)
![Screenshot 2022-09-04 170057](https://user-images.githubusercontent.com/104320194/188311106-78b86153-67bc-4986-9991-ab59254fce87.jpeg)

**Comment by Sai3Rahul** [comment]
![image](https://user-images.githubusercontent.com/104320194/189349933-0d754400-cf11-4cb9-accb-d33dbdcb8202.png)

**Comment by Sai3Rahul** [comment]
![image](https://user-images.githubusercontent.com/104320194/189537447-e8642727-f8f7-4c99-adae-d7a65479ed7e.png)

**Comment by Sai3Rahul** [comment]
![image](https://user-images.githubusercontent.com/104320194/190062350-0a83fc27-8ab3-4551-a7f3-038262ccfedd.png)

**Comment by Sai3Rahul** [comment]
![image](https://user-images.githubusercontent.com/104320194/190171178-8ece5963-42e7-46e6-8fa3-642e9c6a7b35.png)
![image](https://user-images.githubusercontent.com/104320194/190171307-66958cfa-7e7a-406b-8c1b-d6c180e943db.png)
![image](https://user-images.githubusercontent.com/104320194/190171361-f72f74f5-3f14-4818-a5ca-1de3e8bbc1de.png)

**Comment by TeralaShivaKumar** [comment]
hello rahul
It is showing that your pr is closed,please rectify that and mention in server to eligible for rewards

**Comment by Sai3Rahul** [comment]
![image](https://user-images.githubusercontent.com/104320194/190677239-a9197be0-1cb5-4e3d-a01e-7d781a5aca1b.png)

**Comment by Sai3Rahul** [comment]
![Screenshot 2022-09-17 184953](https://user-images.githubusercontent.com/104320194/190859296-708131e1-242b-4525-a273-7b537e60fb1c.jpeg)
![Screenshot 2022-09-17 185015](https://user-images.githubusercontent.com/104320194/190859303-08104e45-8b01-4e27-b9cc-ee99650004ef.jpeg)
![Screenshot 2022-09-17 185054](https://user-images.githubusercontent.com/104320194/190859309-a651ea80-5c74-4adf-9534-08a3240e11e8.jpeg)
![Screenshot 2022-09-17 185435](https://user-images.githubusercontent.com/104320194/190859316-6cf87f47-7794-4fe6-85ac-1897fc5e2ddd.jpeg)

**Comment by Sai3Rahul** [comment]
Scaler 20 challenge 
Project Board link : https://github.com/users/Sai3Rahul/projects/1
![Screenshot 2022-09-21 120605](https://user-images.githubusercontent.com/104320194/191433257-7f1f95af-b405-4a42-8ea4-4c3641843851.jpeg)
![Screenshot 2022-09-21 120638](https://user-images.g
![Screenshot 2022-09-21 121208](https://user-images.githubusercontent.com/104320194/191433310-480c4b0e-ef41-41e4-a14b-10e81021126c.jpeg)
ithubusercontent.com/104320194/191433277-f9ed268f-6f82-4f7d-8acf-86ed2b185cc0.jpeg)
![Screenshot 2022-09-21 121340](https://user-images.githubusercontent.com/104320194/191433332-c0c4bd58-d0b2-4c6c-afd0-7f467560f45e.jpeg)

**Comment by Sai3Rahul** [comment]
Challenge 23:
An overview of what I learned from reading those articles are as follows:
Branches
-> Every project has crucial branches, and these are the
->Main/Master-Default branch and stable branch
->Development is the area where all the changes are made, and it is kept distinct from the main branch.
->QA is where all of the testing is done.
->These branches' names ought to follow the team's overall naming scheme. The branch name may contain terms like "bug fix," "work in progress," "problem it will resolve," "author name," etc.

Issues:-
->We may identify issues related to our interests by using labels, which also helps us determine whether the problem is something we can work on. 
-->If we want to make some modifications that are not described in any issues, we must create a new issue indicating what we want to modify with an appropriate description. Excellent-first-issues labels are typically a good place to start for someone new to open source.

Pull Request:-
->Suitable naming should be used
->Writing suitable commit messages and PR descriptions is important.
->They should have a descriptive titles
->We should review our PR before assigning to others

**Comment by Sai3Rahul** [comment]
Challenge-24 : I have been assigned 2 issues
https://github.com/nuxt/nuxt.js
https://github.com/nidhaloff/igel

**Comment by Sai3Rahul** [comment]
Challenge 25
Forked the repository and started working on it.
![Screenshot 2022-09-25 190954](https://user-images.githubusercontent.com/104320194/192146587-76cc8d15-d296-4cba-9a70-b32c7b85c690.jpeg)

**Comment by Sai3Rahul** [comment]
Challenge 26 :
Today i learned and explored more about open source also i tried to contribute in 4 projects but ended up with 2 successfull merges
also i will register in hacktoberfest as soon as registrations goes live .
i will update you guys more about my opensource journey soon.

**Comment by Sai3Rahul** [comment]
Challenge 27
Already registered for Hacktoberfest
Gone through the rules and resources provided by Hacktoberfest
For contributing to Hacktoberfest , look for beginner friendly issues called good first issues along with hacktoberfest

NOTE : You all have to make your contributions from Oct 1

Some repositories for Contribution
https://github.com/MrKrishnaAgarwal/Hacktoberfest2022
https://github.com/wagtail/wagtail
More repo [Click here](https://github.com/topics/hacktoberfest)
Most important💯 point to be considered during Hacktoberfest

**Comment by Sai3Rahul** [comment]
Challenge 28 :

**Comment by Sai3Rahul** [comment]
# Challenge 29 ✅

### Discussion created/Fashion website

![image](https://user-images.githubusercontent.com/104320194/193089238-fcadd011-a7d6-4234-bd58-cb63bc11c9b7.png)

### Some upvoted ideas⏫

![Screenshot 2022-09-29 215935](https://user-images.githubusercontent.com/104320194/193089384-b2bd23c2-ba69-4699-8939-34484a4e7842.jpeg)
![image](https://user-images.githubusercontent.com/104320194/193089648-5c620184-3994-44c2-8075-5f605962ef7a.png)

**Comment by Sai3Rahul** [comment]
# Day 30 (Final Day)
I have completed all the challenges, so I will share my experience with this event.
- I got the opportunity to learn GitHub and Git in more advance manner, else I would use git just for pushing and committing changes.
- I thought that I knew git much, but I was astonished to see that there are so many git commands.
- Special Thanks to Scaler Team and Kaizar for giving the opportunity to learn and also get prizes for contributing 😄.
- It's the final day of the challenge (Day-30) and I've successfully completed all of it. Thanks to Scaler team for the open source challenge event and also everyone in the community who helped to complete the task when I got stuck in it.
- I was completely new to this but after completing this challenge, I've learned a lot of things about Git and GitHub and gained knowledge on open-source. I'll be looking forward to participate in Hacktoberfest and also contributing to more open-source projects.
- Finally, the day came which is the end of 30 days of scaler open source challenge 2022. I had an amazing experience in this by learning about git, GitHub, and how to contribute to open source projects.
- Thanks for conducting this challenge - A challenge where there is nothing to lose only your knowledge in the field of GitHub will increase.
- I want to say a big thank you to all the community members, especially @shivaylamba  sir, for sharing his amazing knowledge about open source and giving opportunities to others to learn.

**Comment by kuraakhilesh8230** [comment]
congrats you have completed milestone-4 successfully and you are good to go🎉

**Comment by Sai3Rahul** [comment]
Thank u my friend
