### ISSUE TITLE
Challenge 30

### ISSUE THREAD

**Issue by siddhesh3607** [scaleracademy/scaler-september-open-source-challenge#367]
name : Siddhesh Vilas Sawant
github_user_name : siddhesh3607

URL of your forked repository : https://github.com/siddhesh3607/scaler-september-open-source-challenge

A screenshot of the cloned project in your system 

![Screenshot (24)](https://user-images.githubusercontent.com/100701921/188202345-9a7168b0-1a5e-4146-a989-f809018f0c19.png)

Screenshot showing the list of all the current branches inside of your forked clone repository:

![Screenshot (26)](https://user-images.githubusercontent.com/100701921/188278094-ee37b0e6-5d44-4c36-9aac-8564a1f86804.png)

![Screenshot (29)](https://user-images.githubusercontent.com/100701921/188319924-33ad88c5-66bb-47a4-950c-127bf507070b.png)

git reset
![Screenshot (37)](https://user-images.githubusercontent.com/100701921/189414799-23448c57-1aaf-4c80-9afc-d01642687801.png)
challenge 10
![Screenshot (40)](https://user-images.githubusercontent.com/100701921/189496902-2f765091-89d4-499c-afe5-24692846415e.png)
 
Challenge 11

![Screenshot (44)](https://user-images.githubusercontent.com/100701921/189540379-420bd540-5bc2-426b-a52a-020275549c11.png)
 
challenge 13 stash file

![Screenshot (47)](https://user-images.githubusercontent.com/100701921/189948012-dd4430a2-5b44-48ce-a012-8cf5e5c9caa9.png)

challenge 14

![Screenshot (49)](https://user-images.githubusercontent.com/100701921/190225330-d792219c-9ee7-4eb9-8a0f-7275eeba3ff9.png)

![Screenshot (50)](https://user-images.githubusercontent.com/100701921/190225363-7bf60f3f-0bab-499b-8a67-7bc8fe3d1e77.png)
 
challenge 15

![Screenshot (53)](https://user-images.githubusercontent.com/100701921/190458955-cd8e037c-37ee-4013-b197-a6b7f8690d51.png)

![Screenshot (55)](https://user-images.githubusercontent.com/100701921/190459002-7545dd4b-0296-4893-9080-409b9aa6d7c7.png)

challenge 16
![Screenshot (60)](https://user-images.githubusercontent.com/100701921/190843674-498dbd11-c569-4de5-99db-7f4924389b78.png)

challenge 17

1. Installed GitHub Desktop

2. Create a new branch

![Screenshot (65)](https://user-images.githubusercontent.com/100701921/190886958-8ecb71c2-ca2d-4e0f-b81c-9841e6f523b5.png)

3.Edit a file

![Screenshot (62)](https://user-images.githubusercontent.com/100701921/190886986-2f4ccd73-dc8f-4fb4-a0cd-bd30d6ba38b6.png)

4. Make a commit

![Screenshot (63)](https://user-images.githubusercontent.com/100701921/190887003-625e9b7e-d44a-4b90-b30d-b13bdccfed9b.png)

5.Publish to GitHub

![Screenshot (68)](https://user-images.githubusercontent.com/100701921/190887027-6aa47eb8-f90c-4dd5-8f99-1c0530c29748.png)

6. Open a pull request

![Screenshot (74)](https://user-images.githubusercontent.com/100701921/190887066-375b7830-3857-43ed-8851-9661659765fc.png)

challenge 20

GitHub repository Link for my project:https://github.com/siddhesh3607/college-Inauguration
Created a Project Board for my repository:https://github.com/users/siddhesh3607/projects/3/views/1

Step 1 : Project board created
![Screenshot (6)](https://user-images.githubusercontent.com/100701921/191835964-c6d1107f-e61b-4b57-8695-743037ddbaaf.png)

Step 2 : Issues created
![Screenshot (7)](https://user-images.githubusercontent.com/100701921/191836034-69d61174-e4e8-4b66-91dc-c62c8621c158.png)

Step 3 : Solving Issue 1
![Screenshot (9)](https://user-images.githubusercontent.com/100701921/191836109-4ae6a4ca-e86b-4148-9c55-eacfe4d9e742.png)

Step 4 : Solved Issue 1
![Screenshot (10)](https://user-images.githubusercontent.com/100701921/191836166-93cb859f-0174-4aff-bd1d-542ed3fed3a4.png)

Step 5 : Solving Issue 2
![Screenshot (11)](https://user-images.githubusercontent.com/100701921/191836265-a7e490bd-d4ad-4f59-9899-d2a132224691.png)

Step 6 : Solved Issue 2
![Screenshot (12)](https://user-images.githubusercontent.com/100701921/191836329-66a6407a-543c-4806-a663-dc78453d4a7a.png)

Step 7 : Issue in progress
![Screenshot (13)](https://user-images.githubusercontent.com/100701921/191836508-f4b7e794-438e-480f-a14a-937d93c7d71d.png)

Step 8 : Closed Issues
![Screenshot (14)](https://user-images.githubusercontent.com/100701921/191836633-0c111c04-e78f-45a0-b46a-a4ddfb97c510.png)

Challenge 21

![Screenshot (2)](https://user-images.githubusercontent.com/100701921/191563210-2797a5aa-2bd4-47fe-a0f0-24585b277ade.png)

![Screenshot (3)](https://user-images.githubusercontent.com/100701921/191563265-2dad9a3e-c7b4-4b10-8d0e-7f2737f236bc.png)

Challenge 23:

Branches
1 -The important branches in any project is the
-Main Stable version
-Development -Where all the changes take place
-QA - Where all the testing takes place
2 -The branches we will be working on has to be named as per a standard. For example, the branch name can include words
like bug, fix, WIP, etc, the issue it will be solving, author name, etc.
3 -The name of these branches should match with the naming convention of the rest of the team.

Pull requests
1 -The pull request created should be descriptive of the problem that is being solved.
2 -It should refer to the issue which the pull request closes.
3 -The pull request should be created from a feature branch of the forked repo and not the main.
4 -The changes should be reviewed and tested before creating pull request.

Issues
1-Always see for good-first-issue in the repos
2-Avoid long descriptive names
3-Create only meaningful issues

Challenge 24 

Status :
Currently looking for issues that I am able to contribute to. I explored many issues but mostly people had listed complex issues which are , as of now , beyond my contributing knowledge. I will soon update this when I find a suitable issue to contribute.

Challenge 25

I have requested to provide contribution for one issue. Waiting for it to be assigned to myself.

https://github.com/kishanrajput23/Hacktoberfest-2022/issues/1#issue-1385125425

Challenge   26
Registered for Hacktoberfest 2022 as Contributor

![1](https://user-images.githubusercontent.com/100701921/193055679-84901c69-f07b-465a-aaf2-a53653a06347.png)

Challenge   27

Contributors Guidelines
Register anytime between September 26 and October 31.

Pull requests can be made in any GitHub or GITLAB hosted project that’s participating in Hacktoberfest.

Project maintainers must accept your pull/merge requests for them to count toward our total.

Have 4 pull/merge requests accepted between October 1 and October 31 to complete Hacktoberfest.

Only first 40,000 participants (maintainers and contributors) who complete Hacktoberfest can elect to receive one of two prizes: a tree planted in their name, or the Hacktoberfest 2022 t-shirt.

Resources For Beginners
DigitalOcean : Introduction To GitHub and Open Source Projects

GitHub : How To Contribute To Open Source

DigitalOcean : What is Open Source

DigitalOcean : How To Use Git

Challenge   28

I have requested to provide contribution for one issue. Waiting for it to be assigned to myself.

Challenge   29

Programming Club Discussion Website for College Students #63

![12](https://user-images.githubusercontent.com/100701921/193058979-d2f5b74f-7033-4ad3-ba2a-f32346ea90cc.png)

Challenge   30

Successfully completed all the challenges. Thanks to Scaler for organizing it, everyone in the community was helpful and encouraged a lot during these 30 days. It was a great learning experience with Scaler Open-Source. As I was a beginner to GitHub so I didn't have even the basic knowledge of using GitHub, but due to these challenges only I was able to learn and understand many new and important things.
Lastly,I will continue my journey of open source, really excited about Hactoberfest as this will be the first time I will participate.

**Comment by kuraakhilesh8230** [comment]
when i open your .md file it showing this why ??
it should show box type structure, when we click edit it shows like that but without it it showing check it once
![Screenshot (209)](https://user-images.githubusercontent.com/78216397/190165290-2395fc3a-08f3-41c2-a148-cca32a6ad7ec.png)

**Comment by siddhesh3607** [comment]
> when i open your .md file it showing this why ?? it should show box type structure, when we click edit it shows like that but without it it showing check it once ![Screenshot (209)](https://user-images.githubusercontent.com/78216397/190165290-2395fc3a-08f3-41c2-a148-cca32a6ad7ec.png)

i already try to solve it many time but when i am done with that again the box is disappear so what can i do please guide even i get help from the discord group but again its not working

**Comment by siddhesh3607** [comment]
> Do challenge 20 correctly which should show all your files are done when it moved from inprogress and attach all the screen shots step by step

done please review it

**Comment by kuraakhilesh8230** [comment]
Congrats you have successfully completed milestone 2 and you are good to move onto next milestone
All the best

**Comment by kuraakhilesh8230** [comment]
congrats you have completed the milestone-3 successfully and you are good to go🎉

**Comment by Mrjoy832** [comment]
## Milestone-4 done ✅

**Comment by siddhesh3607** [comment]
I already done with challenge but don't find any issues yet to contribute
