### ISSUE TITLE
Challenge 11 of 30

### ISSUE THREAD

**Issue by kitt555** [scaleracademy/scaler-september-open-source-challenge#38]
name: Ankit Bhowmick
github_user_name: kitt555

**Comment by kitt555** [comment]
- URL of your forked repository: https://github.com/kitt555/scaler-september-open-source-challenge.git
 - A screenshot of the cloned project in your system: 
![2022-09-02 (1)](https://user-images.githubusercontent.com/105461062/188092236-ae43ad20-03cc-409d-8d4b-423e2e558c7f.png)

**Comment by kitt555** [comment]
- Screenshot showing the list of all the current branches inside of your forked clone repository:
![2022-09-03 (3)](https://user-images.githubusercontent.com/105461062/188262155-53e76762-b93e-4eb2-b7b3-c1e3b5b72617.png)

**Comment by kitt555** [comment]
- Screenshot showing the list of all the current branches inside of your forked clone repository:
![2022-09-03 (4)](https://user-images.githubusercontent.com/105461062/188263027-4433f964-8867-4a77-99f0-a15fd8e558d5.png)
![2022-09-03 (5)](https://user-images.githubusercontent.com/105461062/188263033-ea90bb63-0f9e-4be5-9a3e-3e03af17f953.png)

**Comment by kitt555** [comment]
Screenshot showing the latest repository contents
![2022-09-04 (1)](https://user-images.githubusercontent.com/105461062/188303419-47b33719-6900-4ad1-9a0b-b3854c671d83.png)
![2022-09-04 (2)](https://user-images.githubusercontent.com/105461062/188303420-faacbd52-0fac-4f8c-9a45-ecc76a57fb8a.png)

**Comment by kitt555** [comment]
- Identify the commit id that needs to be removed (you should have created this in the 8th Challenge)
- Use git reset and force push, to remove the commit from your pull request.
- Share a screenshot of this, in the issue you created in previous challenges.
![2022-09-10](https://user-images.githubusercontent.com/105461062/189431851-7e75f796-5a7c-4528-8cc0-12f79da7c888.png)

**Comment by kitt555** [comment]
Edited the md file
![2022-09-10 (4)](https://user-images.githubusercontent.com/105461062/189480494-0df553e9-0e98-4fa7-80b5-fa3d52150458.png)
![2022-09-10 (5)](https://user-images.githubusercontent.com/105461062/189480497-4827dfeb-e70a-4eaf-8e21-d5bc83e34c5e.png)

**Comment by kitt555** [comment]
Completed challenge 11:

![2022-09-11 (6)](https://user-images.githubusercontent.com/105461062/189535079-b0b92846-c4d7-4a1a-9f96-43cb4a5055eb.png)
![2022-09-11 (5)](https://user-images.githubusercontent.com/105461062/189535086-b9293a9f-6580-475b-92e9-6b93ff63c025.png)

**Comment by DaltonDeven** [comment]
Thanks for putting in the effort we appreciate it very much, you can continue to take part in the challenge , but wont be eligible for the rewards because there are 0 commits in the PR and the PR is closed
