### ISSUE TITLE
Challenge 1-4, 9, 11, 13-14, 16-17, 20-21, 23-30

### ISSUE THREAD

**Issue by Rakesh9100** [scaleracademy/scaler-september-open-source-challenge#418]
name: Rakesh Roshan
github_user_name: Rakesh9100

**Comment by Rakesh9100** [comment]
URL of your forked repository :
https://github.com/Rakesh9100/scaler-september-open-source-challenge

A screenshot of the cloned project in your system :
![clone](https://user-images.githubusercontent.com/73993775/188213247-d3e8dc7b-af29-42c1-8b9b-80180ebcf76c.png)

**Comment by Rakesh9100** [comment]
Screenshot showing the list of all the current branches inside of your forked clone repository :

![Screenshot](https://user-images.githubusercontent.com/73993775/188266514-c207aa8f-772f-4482-8695-6d30fd96df59.png)

**Comment by Rakesh9100** [comment]
Screenshot showing the latest repository contents :

![Screenshot](https://user-images.githubusercontent.com/73993775/188320913-fcbfdc66-ad5f-4d5f-93a9-006c1782b6db.png)

**Comment by Rakesh9100** [comment]
Challenge 9 :
![Challenge9](https://user-images.githubusercontent.com/73993775/189412821-55616ce4-1e95-45e5-81f8-4e73aca27332.png)

**Comment by Rakesh9100** [comment]
Screenshot of new branch :
![Screenshot](https://user-images.githubusercontent.com/73993775/189544053-26a48444-e9e9-4e17-bbe4-721f227ebd95.jpg)

**Comment by Rakesh9100** [comment]
Screenshot of Challenge 13 :
![Challenge13](https://user-images.githubusercontent.com/73993775/189990814-66b54ec5-3299-4764-aba5-efdda6dbeb34.png)

**Comment by Rakesh9100** [comment]
## Challenge 14 :
### Screenshot 1
![S1](https://user-images.githubusercontent.com/73993775/190222687-6b419a63-a9f9-41b3-8a22-bd6ffee3460d.png)
### Screenshot 2
![S2](https://user-images.githubusercontent.com/73993775/190222735-51242e5b-c273-4c06-9af1-5eb6817558fc.png)

**Comment by Rakesh9100** [comment]
# Challenge 17 : Interacting with GitHub Desktop
## Repository Link :- https://github.com/Rakesh9100/Challenge-17
## 1. Installed GitHub Desktop on my System
![1](https://user-images.githubusercontent.com/73993775/190874665-b07de588-4586-413c-a491-24b3a8330f75.png)
## 2. Creating a new repo
![2](https://user-images.githubusercontent.com/73993775/190874711-c729aba6-db81-46e4-8009-af3a4dca15b0.png)
## 3. New repo created locally
![3](https://user-images.githubusercontent.com/73993775/190874715-4fb2d606-e6de-4ccc-9234-8ccaaa733f4d.png)
## 4. Editing the Readme.md for a new commit
![4](https://user-images.githubusercontent.com/73993775/190874724-bd1f1822-a06b-4cb6-8bb3-2b5bf55afe54.png)
## 5. New commit "Readme Update"
![6](https://user-images.githubusercontent.com/73993775/190874741-c497fc68-318d-44ea-85c2-03e1286c2e1f.png)
## 6. Pushed the repo and commits to the remote
![7](https://user-images.githubusercontent.com/73993775/190874776-c1da4c13-cbe4-41e1-b891-c3ea2c4b168c.png)
## 7. Creating a new branch "challenge-17"
![8](https://user-images.githubusercontent.com/73993775/190874787-9f692fe5-bb17-4112-819d-b0dcd4271ea0.png)
## 8. Pushed and updated the branch in the remote repo
![10](https://user-images.githubusercontent.com/73993775/190874794-c2b3db6e-87c0-4d03-a0bb-f2b70250838f.png)
## 9.  Making change in Readme.md in the branch "challenge-17" to work with new Pull Request
![11](https://user-images.githubusercontent.com/73993775/190875153-c7c28f1d-4675-479e-8d56-39e3c2f21f69.png)
## 10.  Pushed the change to the remote to create a PR
![12](https://user-images.githubusercontent.com/73993775/190875154-a967eb42-ea97-4d19-a3c6-8f746ec1f232.png)
## 11. Created the PR showing the changes
![13](https://user-images.githubusercontent.com/73993775/190875158-404b2b07-d0c4-4203-987b-d92c27ebe6a0.png)

**Comment by Rakesh9100** [comment]
# Challenge 20 :

## Link of the repo for which project tasks was done : 
<https://github.com/Rakesh9100/Challenge-20>

## Screenshot of the project board : 
![1](https://user-images.githubusercontent.com/73993775/191333068-cd82b9c8-df92-485f-9985-37489a1f7fcf.png)

**Comment by Rakesh9100** [comment]
# Challenge 21 : 

## Screenshot of alias created
![custom](https://user-images.githubusercontent.com/73993775/191496586-95b05ce2-ec59-4fed-857f-e1f560785a65.png)

## Screenshot of using alias
![used](https://user-images.githubusercontent.com/73993775/191496593-a25dd712-55b9-4033-9b0c-6bf23e2908f0.png)

**Comment by kuraakhilesh8230** [comment]
Congrats you have successfully completed milestone 2 and you are good to move onto next milestone all the best 👏 👏

**Comment by Rakesh9100** [comment]
# Challenge 23:

## What needs to be done for effective open source contribution:

## Issues:
- If you are a beginner, always start with a `good-first-issue` tagged issue.
- If you want to make some changes not specified in any issues, or you find any bug, first create a new issue and wait until it's assigned to you.

## PRs:
- Write description well.
- Mention reference issue.
- Review changes before creating a pull request.

## Tips:
- Give your feature branch a clear name.
- Give your commits and PRs active and descriptive titles.
- Streamline your process of creating a new PR.
- Give your PR a meaningful description.
- Show your functionality visually, whenever possible.
- Review your own PR before you assign it to others.

## Contribution Guidelines
- Before contributing into any repository, first check out the guidelines of how to contribute inside the repository. You can find it in the README.md file, or there will be a separate `Contributing Guidelines.md` file. Go through it and follow it.

## Contribution process
- Once you've found an issue you'd like to work on:
- Comment on it and say you're working on that issue. This is to avoid conflicts with others also working on the issue.
- Write your code and submit your pull request
- Wait for code review and address any issues raised as soon as you can.
- However, if staff-only label is there then you are not allowed to contribute as these are for the staff only.

**Comment by Rakesh9100** [comment]
# Challenge 24 : 
## Issues assigned : 
- https://github.com/aritra-tech/Data-Structure-Algorithm/issues/425
- https://github.com/aritra-tech/Data-Structure-Algorithm/issues/424

**Comment by Rakesh9100** [comment]
# Challenge 25 : 
Worked on the assigned issues.
- https://github.com/aritra-tech/Data-Structure-Algorithm/issues/425

**Comment by Rakesh9100** [comment]
# Challenge 26 : 
## Registered for Hacktoberfest : 
![image](https://user-images.githubusercontent.com/73993775/193327370-5f6181aa-ac22-4d10-b504-2cf0a88138c0.png)

**Comment by Rakesh9100** [comment]
# Challenge 27 : 

## Contribution Guidelines : 
- Register anytime between September 26 and October 31.

- Pull requests can be made in any GitHub or GITLAB hosted project that’s participating in Hacktoberfest.

- Project maintainers must accept your pull/merge requests for them to count toward our total.

- Have 4 pull/merge requests accepted between October 1 and October 31 to complete Hacktoberfest.

- Only first 40,000 participants (maintainers and contributors) who complete Hacktoberfest can elect to receive one of two prizes: a tree planted in their name, or the Hacktoberfest 2022 t-shirt.

**Comment by Rakesh9100** [comment]
# Challenge 28 : 
## Made the PR : 
- https://github.com/aritra-tech/Data-Structure-Algorithm/pull/429
- https://github.com/aritra-tech/Data-Structure-Algorithm/pull/428

**Comment by Rakesh9100** [comment]
# Challenge 29 : 
## Upvoted certain ideas
- https://github.com/scaleracademy/open-source-projects/discussions/45
- https://github.com/scaleracademy/open-source-projects/discussions/63

**Comment by Rakesh9100** [comment]
# Challenge 30 : 

- I got to learn so many new things through this challenge.
- I only knew a few basic commands of git earlier but with these challenges, I learned git and Github in detail.
- Registered for Hacktoberfest 2022 and now will try to make more PRs.
- Thank you Scaler Academy for organizing such a wonderful event.

**Comment by kuraakhilesh8230** [comment]
Congrats you have successfully completed milestone 4 🎊
