### ISSUE TITLE
Challenge 2

### ISSUE THREAD

**Issue by mridulgoel03** [scaleracademy/scaler-september-open-source-challenge#463]
name : Mridul Goel
github_user_name : mridulgoel03

URL : https://github.com/mridulgoel03/scaler-september-open-source-challenge

Screenshot
![image](https://user-images.githubusercontent.com/91424191/188200518-a192c24e-c7fb-4af8-9050-d4b008ba99b1.png)

**Comment by shivaylamba** [comment]
YOu had to create the comment inside the first issue you created, you didnt have to create a new issue. This is not the task
