### ISSUE TITLE
Challenge 2

### ISSUE THREAD

**Issue by saxam0** [scaleracademy/scaler-september-open-source-challenge#465]
URL of forked repository - https://github.com/saxam0/scaler-september-open-source-challenge

Screenshot of the cloned project in your system
![image](https://user-images.githubusercontent.com/97455464/188206243-79e2be51-ab0c-4448-912b-ee1905a8018a.png)

**Comment by shivaylamba** [comment]
YOu had to create the comment inside the first issue you created, you didnt have to create a new issue. This is not the task
