### ISSUE TITLE
Challenges 2 

### ISSUE THREAD

**Issue by prashant31299** [scaleracademy/scaler-september-open-source-challenge#468]
url : - https://github.com/prashant31299/scaler-september-open-source-challenge

screenshot

<img width="1221" alt="Screenshot 2022-09-02 at 11 11 24 PM" src="https://user-images.githubusercontent.com/86360295/188209183-66470978-501b-4991-af0d-88a913412f6a.png">

**Comment by prashant31299** [comment]
challenge 2

**Comment by shivaylamba** [comment]
YOu had to create the comment inside the first issue you created, you didnt have to create a new issue. This is not the task
