### ISSUE TITLE
challange 2

### ISSUE THREAD

**Issue by nitishgiri007** [scaleracademy/scaler-september-open-source-challenge#469]
https://github.com/nitishgiri007/scaler-september-open-source-challenge
![challange 2](https://user-images.githubusercontent.com/85404432/188210284-b4411d80-7ed0-4755-aeef-ba8d99b3c0b7.PNG)

**Comment by shivaylamba** [comment]
You don't have to create a separate issue. It has to be on the same issue as you had created for first.

**Comment by nitishgiri007** [comment]
Can I continue or not???
